services:
  casnode1:
    image: cassandra
    container_name: casnode1
    ports:
      - "127.0.0.1:9042:9042"
    networks:
      - cassandraNet

  casenode2:
    image: cassandra
    container_name: casnode2
    depends_on:
      - casnode1
    ports:
      - "127.0.0.2:9042:9042"
    environment:
      - CASSANDRA_SEEDS=casnode1
    networks:
      - cassandraNet

  # casnode3:
  #   image: cassandra
  #   container_name: casnode3
  #   depends_on:
  #     - casnode1
  #   ports:
  #     - "9044:9042"
  #   environment:
  #     - CASSANDRA_SEEDS=casnode1
  #   networks:
  #     - cassandraNet

networks:
  cassandraNet:
    driver: bridge
    